version: '3'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: metalkat
      POSTGRES_PASSWORD: metalkat-password
      POSTGRES_DB: metalkat-db